// //number
// let ab=80.6
// console.log(ab);

// //boolean
// let b=false
// console.log(typeof b)

// //undefined
// let a;
// console.log(typeof a);

// let c=''
// console.log(typeof c);

// let c1=null
// console.log(typeof c1) 


// //object
// let browser={
//     name:"chrome",
//     version:"48.3",
//      env:"FIN"
// }

// console.log(browser.name);
// console.log(typeof browser);
// console.log(browser.env);

//Array

let browser1=[{
    name:"chrome",
    version:"48.3",
     env:"FIN"
},
{
    name:"firefox",
    version:"48.5",
     env:"FAC"
}]
console.log(browser1[1].name);
console.log(typeof browser1);
console.log(browser1[1].env);
console.table(browser1);

//test