// function test(){
// var a=8;
// for (var a=0;a<7;a++)
// {
//  console.log(a);
// }
// console.log(a);
// }
//  test();

function add(a,b,c)  {
    console.log(a+b+c)
 }
 add(1,2,3);

function sub(a,b,v){
    console.log(100-(a+b+v));
 }
sub(1,3,3);


let testing=function multiple(a,b,c)
{
    console.log(a*b*c)
}
testing(1,1,1);


let testing1=() =>{
  

    console.log(a*b*c)
}
testing(1,1,3);

let a="jakaka";
let b="hello"
console.log(a.concat(b))
